-- =====================================================
-- Table features
-- =====================================================
CREATE TABLE shop.features (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	code VARCHAR(55) UNIQUE,
	name VARCHAR(55) NOT NULL,
	url VARCHAR(55) UNIQUE,
	created TIMESTAMPTZ DEFAULT now(),
	updated TIMESTAMPTZ
);

-- =====================================================
-- Trigger for Table features
-- =====================================================
CREATE TRIGGER trg_features_updated
BEFORE UPDATE ON shop.features
FOR EACH ROW
EXECUTE FUNCTION shop.set_updated_timestamp();

-- =====================================================
-- Seed default value into table features
-- =====================================================
INSERT INTO shop.features (code, name, url) VALUES
-- Admin
('FEATURE_MANAGE_USERS', 'Manage Users', '/admin/users'),
('FEATURE_MANAGE_ROLES', 'Manage Roles', '/admin/roles'),
('FEATURE_MANAGE_PERMISSIONS', 'Manage Permissions', '/admin/permissions'),
('FEATURE_MANAGE_SETTINGS', 'System Settings', '/admin/settings'),
('FEATURE_VIEW_DASHBOARD', 'View Dashboard', '/admin/dashboard'),

-- Product Management
('FEATURE_PRODUCT_LIST', 'Product List', '/products'),
('FEATURE_PRODUCT_DETAIL', 'Product Detail', '/products/{id}'),
('FEATURE_PRODUCT_CREATE', 'Create Product', '/products/create'),
('FEATURE_PRODUCT_UPDATE', 'Update Product', '/products/{id}/edit'),
('FEATURE_PRODUCT_DELETE', 'Delete Product', '/products/{id}/delete'),
('FEATURE_PRODUCT_IMPORT_EXPORT', 'Import/Export Products', '/products/import-export'),

-- Category & Tag
('FEATURE_CATEGORY_LIST', 'Category List', '/categories'),
('FEATURE_CATEGORY_MANAGE', 'Manage Categories', '/categories/manage'),
('FEATURE_TAG_MANAGE', 'Manage Tags', '/tags/manage'),

-- Order Management
('FEATURE_ORDER_LIST', 'Order List', '/orders'),
('FEATURE_ORDER_DETAIL', 'Order Detail', '/orders/{id}'),
('FEATURE_ORDER_UPDATE', 'Update Order', '/orders/{id}/update'),
('FEATURE_ORDER_CANCEL', 'Cancel Order', '/orders/{id}/cancel'),
('FEATURE_ORDER_REFUND', 'Refund Order', '/orders/{id}/refund'),

-- Customer Management
('FEATURE_CUSTOMER_LIST', 'Customer List', '/customers'),
('FEATURE_CUSTOMER_DETAIL', 'Customer Detail', '/customers/{id}'),
('FEATURE_CUSTOMER_UPDATE', 'Update Customer', '/customers/{id}/update'),
('FEATURE_CUSTOMER_BLOCK', 'Block Customer', '/customers/{id}/block'),

-- Marketing & Promotion
('FEATURE_COUPON_MANAGE', 'Manage Coupons', '/marketing/coupons'),
('FEATURE_PROMOTION_MANAGE', 'Manage Promotions', '/marketing/promotions'),
('FEATURE_BANNER_MANAGE', 'Manage Banners', '/marketing/banners'),
('FEATURE_EMAIL_MARKETING', 'Email Marketing', '/marketing/email'),
('FEATURE_ANALYTICS_VIEW', 'View Analytics', '/marketing/analytics'),

-- Sale (POS / Seller)
('FEATURE_SALE_VIEW_PRODUCTS', 'View Products (POS)', '/sale/products'),
('FEATURE_SALE_MANAGE_CART', 'Manage Customer Cart', '/sale/cart'),
('FEATURE_SALE_CREATE_ORDER', 'Create Order for Customer', '/sale/orders/create'),
('FEATURE_SALE_VIEW_CUSTOMER', 'View Customer (POS)', '/sale/customers'),

-- Customer (End-user)
('FEATURE_CUSTOMER_VIEW_PRODUCTS', 'Browse Products', '/shop/products'),
('FEATURE_CUSTOMER_ADD_TO_CART', 'Add to Cart', '/shop/cart/add'),
('FEATURE_CUSTOMER_VIEW_CART', 'View Cart', '/shop/cart'),
('FEATURE_CUSTOMER_CHECKOUT', 'Checkout', '/shop/checkout'),
('FEATURE_CUSTOMER_TRACK_ORDER', 'Track Order', '/shop/orders/{id}/track'),
('FEATURE_CUSTOMER_REVIEW', 'Write Review', '/shop/products/{id}/review'),
('FEATURE_CUSTOMER_PROFILE', 'Manage Profile', '/shop/profile'),
('FEATURE_CUSTOMER_WISHLIST', 'Wishlist', '/shop/wishlist');
